# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if ENV["JENKINS_HOME"]
    # If we're running in Jenkins, chances are that Jenkins is running on a
    # virtualized server and therefore we must something other than VirtualBox
    # to provide the VM.
    # If this is the case, we default to using lxc.
    config.vm.box = "fgrehm/precise64-lxc"
    config.vm.box_url = "https://vagrantcloud.com/fgrehm/boxes/precise64-lxc/versions/3/providers/lxc.box"
  else
    # Otherwise, just use VirtualBox:
    config.vm.box = "hashicorp/precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end
  end

  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"
  # Folder to share artifacts with jenkins
  config.vm.synced_folder "../..", "/host-workspace"
end
